[toolchain]
package_manager = "yarn"
solana_version = "2.1.0"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
magic_roulette = "B5iruL7jqDXHtWrpBYu9FJVaq5tcgvv7sGLqte5iYRbg"

[programs.devnet]
magic_roulette = "2XxU8pq1HfvB5QAb7snmMPqNsQf8jzQevvJ41JUMzba9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/deepeshsinghrathore/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
