[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
magic_roulette = "RoUnLrec2JvYFMf6ZWnK2wgK8xKaUjwi1GEUPf6fFiF"

[programs.localnet]
magic_roulette = "RoUnLrec2JvYFMf6ZWnK2wgK8xKaUjwi1GEUPf6fFiF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/deepeshsinghrathore/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
